v1_base = {
    'GLOBALEVENTID':         str,
    'SQLDATE':               str,
    'MonthYear':             str,
    'Year':                  str,
    'FractionDate':          str,
    'Actor1Code':            str,
    'Actor1Name':            str,
    'Actor1CountryCode':     str,
    'Actor1KnownGroupCode':  str,
    'Actor1EthnicCode':      str,
    'Actor1Religion1Code':   str,
    'Actor1Religion2Code':   str,
    'Actor1Type1Code':       str,
    'Actor1Type2Code':       str,
    'Actor1Type3Code':       str,
    'Actor2Code':            str,
    'Actor2Name':            str,
    'Actor2CountryCode':     str,
    'Actor2KnownGroupCode':  str,
    'Actor2EthnicCode':      str,
    'Actor2Religion1Code':   str,
    'Actor2Religion2Code':   str,
    'Actor2Type1Code':       str,
    'Actor2Type2Code':       str,
    'Actor2Type3Code':       str,
    'IsRootEvent':           str,
    'EventCode':             str,
    'EventBaseCode':         str,
    'EventRootCode':         str,
    'QuadClass':             str,
    'GoldsteinScale':        str,
    'NumMentions':           str,
    'NumSources':            str,
    'NumArticles':           str,
    'AvgTone':               str,
    'Actor1Geo_Type':        str,
    'Actor1Geo_FullName':    str,
    'Actor1Geo_CountryCode': str,
    'Actor1Geo_ADM1Code':    str,
    'Actor1Geo_Lat':         str,
    'Actor1Geo_Long':        str,
    'Actor1Geo_FeatureID':   str,
    'Actor2Geo_Type':        str,
    'Actor2Geo_FullName':    str,
    'Actor2Geo_CountryCode': str,
    'Actor2Geo_ADM1Code':    str,
    'Actor2Geo_Lat':         str,
    'Actor2Geo_Long':        str,
    'Actor2Geo_FeatureID':   str,
    'ActionGeo_Type':        str,
    'ActionGeo_FullName':    str,
    'ActionGeo_CountryCode': str,
    'ActionGeo_ADM1Code':    str,
    'ActionGeo_Lat':         str,
    'ActionGeo_Long':        str,
    'ActionGeo_FeatureID':   str,
    'DATEADDED':             str,
    'SOURCEURL':             str
}

v1_adds = [
    'TITLE',
    'SITE',
    'SUMMARY',
    'KEYWORDS',
    'META'
]